version: '3'

services:
  emqx:
    image: emqx/emqx:5.3
    container_name: emqx
    networks:
      - my-network
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=node1.emqx
      - EMQX_NODE__DIST_LISTEN_MIN=6369
      - EMQX_NODE__DIST_LISTEN_MAX=6379
      - EMQX_LISTENER__TCP__EXTERNAL=1883
      - EMQX_LOADED_PLUGINS=emqx_recon,emqx_retainer,emqx_management,emqx_auth_username
    ports:
      - 1883:1883
      - 8883:8883
      - 8083:8083
      - 18083:18083

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 15672:15672 # porta da dashboard web -> localhost:15672
      - 5672:5672 # porta do broker
      - 15692:15692
    networks:
      - my-network

  rmq-bridge:
    image: rmq-bridge
    container_name: rmq-bridge
    networks:
      - my-network
    environment:
      - RUST_LOG=debug

      - MQTT_HOST=localhost
      - MQTT_PROTOCOL=tcp
      - MQTT_PORT=1883
      - MQTT_CLIENT_ID=mqtt-explorer-1234
      - MQTT_USERNAME=user
      - MQTT_PASSWORD=user

      - RABBITMQ_HOST=localhost
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest

  device-simulator:
    image: device-simulator
    container_name: device-simulator
    networks:
      - my-network
    environment:
      - MQTT_HOST=emqx:1883
      - MQTT_PROTOCOL=tcp

networks:
  my-network:
    driver: bridge